/**
 * VI超市 商品数据
 * 按行业垂直生产的标准VI套装
 */
import { VIProduct } from './types';

export const VI_PRODUCTS: VIProduct[] = [
  // ===== 餐饮 =====
  {
    id: 'vi_cafe_01', name: '晨雾咖啡', subtitle: '日式冷淡 · 木质温暖',
    industry: 'food', subcategory: '咖啡馆', tags: ['咖啡馆', '原木风', '日式'],
    primaryColor: '#8B6F47', secondaryColor: '#D4C4A8', accentColor: '#E8DCC8',
    neutralColor: '#6B6560', bgColor: '#FAF7F2',
    fonts: { heading: 'Noto Serif SC', body: 'Noto Sans SC' },
    logoText: '晨雾', logoIcon: '咖啡杯+蒸汽',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: 'Spark 官方', sales: 328, rating: 4.8, isExclusive: false, isNew: false, isFeatured: true,
    story: '灵感来源于京都街头的小巧咖啡馆。去除一切不必要的装饰，只保留木材质的温暖与咖啡的醇香。',
    designConcept: '以"减法"为核心，用大量留白和暖棕色系营造安静的第三空间感。',
    mockups: { card: '牛皮纸质感名片', storefront: '木质招牌+暖光', phone: '小红书咖啡日记', packaging: '牛皮纸咖啡袋' },
  },
  {
    id: 'vi_tea_01', name: '山间茶语', subtitle: '新中式 · 禅意留白',
    industry: 'food', subcategory: '茶饮', tags: ['茶饮', '国风', '禅意'],
    primaryColor: '#556B2F', secondaryColor: '#8FBC8F', accentColor: '#DAA520',
    neutralColor: '#5C5C5C', bgColor: '#F5F5EC',
    fonts: { heading: 'ZCOOL XiaoWei', body: 'Noto Sans SC' },
    logoText: '山间', logoIcon: '茶叶+山形',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: 'Spark 官方', sales: 512, rating: 4.9, isExclusive: false, isNew: false, isFeatured: true,
    story: '传统茶文化与现代生活方式的碰撞。一杯茶，一座山，一段安静的时光。',
    designConcept: '水墨留白+现代排版，用绿色系传递自然与健康。',
    mockups: { card: '宣纸质感名片', storefront: '竹帘+木质门头', phone: '抖音茶艺短视频封面', packaging: '茶叶罐+手提袋' },
  },
  {
    id: 'vi_bakery_01', name: '麦穗时光', subtitle: '法式温馨 · 奶油暖调',
    industry: 'food', subcategory: '烘焙', tags: ['烘焙', '法式', '温馨'],
    primaryColor: '#D4956A', secondaryColor: '#F2E0C9', accentColor: '#C0392B',
    neutralColor: '#7D6B5D', bgColor: '#FFF8F0',
    fonts: { heading: 'Playfair Display', body: 'Noto Sans SC' },
    logoText: '麦穗', logoIcon: '麦穗+面包',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: '设计师 @Momo', sales: 189, rating: 4.7, isExclusive: false, isNew: true, isFeatured: false,
    story: '每一个清晨，都从新鲜出炉的面包香气开始。',
    designConcept: '奶油色为底，搭配手绘风插画元素，传递手作的温度。',
    mockups: { card: '圆角奶油色名片', storefront: '法式遮阳棚门头', phone: '公众号面包教程', packaging: '牛皮纸面包袋' },
  },
  {
    id: 'vi_hotpot_01', name: '红炉记', subtitle: '热辣国潮 · 烟火气',
    industry: 'food', subcategory: '火锅', tags: ['火锅', '国潮', '热辣'],
    primaryColor: '#C0392B', secondaryColor: '#E74C3C', accentColor: '#F39C12',
    neutralColor: '#4A4A4A', bgColor: '#FFF5F5',
    fonts: { heading: 'ZCOOL KuaiLe', body: 'Noto Sans SC' },
    logoText: '红炉', logoIcon: '火锅+火焰',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: 'Spark 官方', sales: 267, rating: 4.6, isExclusive: false, isNew: false, isFeatured: false,
    story: '三五好友，一口红锅，这就是中国人的社交方式。',
    designConcept: '大红+金色的经典国潮配色，粗犷有力的字体传递烟火气。',
    mockups: { card: '红底烫金名片', storefront: '霓虹灯招牌', phone: '抖音探店封面', packaging: '火锅底料包装' },
  },

  // ===== 零售 =====
  {
    id: 'vi_fashion_01', name: '素然', subtitle: '极简黑白 · 先锋态度',
    industry: 'retail', subcategory: '服饰', tags: ['服饰', '极简', '先锋'],
    primaryColor: '#1A1A1A', secondaryColor: '#333333', accentColor: '#FFFFFF',
    neutralColor: '#999999', bgColor: '#FAFAFA',
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    logoText: 'SURAN', logoIcon: '几何线条',
    pricing: { basic: 129, standard: 249, premium: 499 },
    creator: 'Spark 官方', sales: 412, rating: 4.9, isExclusive: false, isNew: false, isFeatured: true,
    story: '回归服装本身的剪裁与质感。极致的黑白灰，彰显主理人不妥协的时尚态度。',
    designConcept: '纯黑白+大量留白+粗野主义排版，让产品本身成为唯一焦点。',
    mockups: { card: '黑卡纸白字名片', storefront: '纯白门头+黑字', phone: '小红书穿搭分享', packaging: '黑色磨砂手提袋' },
  },
  {
    id: 'vi_beauty_01', name: '柔光', subtitle: '轻奢裸色 · 高级感',
    industry: 'retail', subcategory: '美妆', tags: ['美妆', '轻奢', '裸色'],
    primaryColor: '#C9A87C', secondaryColor: '#E8D5C4', accentColor: '#8B6F47',
    neutralColor: '#9C8E82', bgColor: '#FBF8F4',
    fonts: { heading: 'Cormorant Garamond', body: 'Noto Sans SC' },
    logoText: '柔光', logoIcon: '光晕+花瓣',
    pricing: { basic: 129, standard: 249, premium: 499 },
    creator: '设计师 @Luna', sales: 356, rating: 4.8, isExclusive: false, isNew: true, isFeatured: true,
    story: '每个女生都值得被温柔以待。柔光，让美回归自然。',
    designConcept: '裸粉+香槟金，衬线体标题传递优雅，整体克制而高级。',
    mockups: { card: '烫金裸粉名片', storefront: '大理石+金属门头', phone: '小红书美妆测评', packaging: '磁吸礼盒' },
  },
  {
    id: 'vi_pet_01', name: '毛球星球', subtitle: '活泼可爱 · 萌系治愈',
    industry: 'retail', subcategory: '宠物', tags: ['宠物', '可爱', '治愈'],
    primaryColor: '#FF8C42', secondaryColor: '#FFD166', accentColor: '#06D6A0',
    neutralColor: '#7B7B7B', bgColor: '#FFFDF7',
    fonts: { heading: 'ZCOOL KuaiLe', body: 'Noto Sans SC' },
    logoText: '毛球', logoIcon: '猫爪+星球',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: 'Spark 官方', sales: 178, rating: 4.7, isExclusive: false, isNew: false, isFeatured: false,
    story: '在毛球星球，每一个毛孩子都是宇宙的中心。',
    designConcept: '高饱和暖色+圆润图形，传递快乐和治愈感。',
    mockups: { card: '圆角彩色名片', storefront: '卡通门头+爪印', phone: '抖音萌宠视频', packaging: '宠物零食袋' },
  },

  // ===== 科技 =====
  {
    id: 'vi_saas_01', name: 'FlowBase', subtitle: '现代扁平 · 效率至上',
    industry: 'tech', subcategory: 'SaaS', tags: ['SaaS', '现代', '效率'],
    primaryColor: '#3A86FF', secondaryColor: '#8338EC', accentColor: '#06D6A0',
    neutralColor: '#6B7280', bgColor: '#F8FAFC',
    fonts: { heading: 'Inter', body: 'Inter' },
    logoText: 'Flow', logoIcon: '流线+节点',
    pricing: { basic: 129, standard: 249, premium: 499 },
    creator: 'Spark 官方', sales: 289, rating: 4.8, isExclusive: false, isNew: false, isFeatured: true,
    story: '让工作像水一样流动。FlowBase，重新定义团队协作。',
    designConcept: '蓝紫渐变+几何图形+大量白空间，传递专业与创新。',
    mockups: { card: '白底蓝字名片', storefront: '科技园区门牌', phone: '产品官网移动端', packaging: '周边贴纸' },
  },
  {
    id: 'vi_ai_01', name: 'NeuralPulse', subtitle: '未来感 · 深邃科技',
    industry: 'tech', subcategory: 'AI', tags: ['AI', '未来感', '深邃'],
    primaryColor: '#6C5CE7', secondaryColor: '#0984E3', accentColor: '#00CEC9',
    neutralColor: '#636E72', bgColor: '#F0F3FF',
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    logoText: 'Neural', logoIcon: '神经网络节点',
    pricing: { basic: 149, standard: 299, premium: 599 },
    creator: '设计师 @Neo', sales: 156, rating: 4.7, isExclusive: false, isNew: true, isFeatured: false,
    story: '在数据的脉搏中，发现智能的边界。',
    designConcept: '紫蓝渐变+网格线+粒子效果暗示，传递前沿科技感。',
    mockups: { card: '深色渐变名片', storefront: 'LED灯牌', phone: '产品Dashboard', packaging: '科技感包装盒' },
  },
  {
    id: 'vi_gaming_01', name: '赛博竞技', subtitle: '霓虹高饱和 · 电竞热血',
    industry: 'tech', subcategory: '游戏', tags: ['电竞', '霓虹', '热血'],
    primaryColor: '#00FF41', secondaryColor: '#FF006E', accentColor: '#FFBE0B',
    neutralColor: '#2D3436', bgColor: '#0A0A0A',
    fonts: { heading: 'Orbitron', body: 'Teko' },
    logoText: 'CYBER', logoIcon: '机甲头盔',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: '设计师 @Neo', sales: 98, rating: 4.5, isExclusive: false, isNew: false, isFeatured: false,
    story: '专为次世代电竞体验打造。黑绿配色，硬朗机甲风。',
    designConcept: '高对比度黑绿+切割线条+故障艺术元素。',
    mockups: { card: '黑卡荧光绿名片', storefront: 'LED霓虹招牌', phone: '战队社媒主页', packaging: '电竞外设包装' },
  },

  // ===== 教育 =====
  {
    id: 'vi_kids_01', name: '小星球', subtitle: '糖果色 · 快乐成长',
    industry: 'edu', subcategory: '早教', tags: ['早教', '活泼', '糖果色'],
    primaryColor: '#FF6B6B', secondaryColor: '#4ECDC4', accentColor: '#FFE66D',
    neutralColor: '#7B7B7B', bgColor: '#FFFEF7',
    fonts: { heading: 'ZCOOL KuaiLe', body: 'Noto Sans SC' },
    logoText: '小星球', logoIcon: '星球+笑脸',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: 'Spark 官方', sales: 234, rating: 4.8, isExclusive: false, isNew: false, isFeatured: false,
    story: '每个孩子都是一颗独特的小星球，等待被发现和照亮。',
    designConcept: '高明度多彩配色+圆润图形+手绘风，传递安全和快乐。',
    mockups: { card: '彩色圆角名片', storefront: '彩虹门头', phone: '家长端小程序', packaging: '教具包装盒' },
  },

  // ===== 健康 =====
  {
    id: 'vi_yoga_01', name: '静界', subtitle: '柔和渐变 · 身心平衡',
    industry: 'health', subcategory: '瑜伽', tags: ['瑜伽', '柔和', '平衡'],
    primaryColor: '#A29BFE', secondaryColor: '#FD79A8', accentColor: '#FFEAA7',
    neutralColor: '#B2BEC3', bgColor: '#F8F7FF',
    fonts: { heading: 'Cormorant Garamond', body: 'Noto Sans SC' },
    logoText: '静界', logoIcon: '莲花+月牙',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: '设计师 @Luna', sales: 145, rating: 4.6, isExclusive: false, isNew: true, isFeatured: false,
    story: '在喧嚣中找到内心的静界。呼吸，感受，回归。',
    designConcept: '紫粉渐变+流线型图形+大量呼吸感留白。',
    mockups: { card: '渐变色名片', storefront: '落地窗+绿植', phone: '预约小程序', packaging: '瑜伽垫包装' },
  },

  // ===== 服务 =====
  {
    id: 'vi_consulting_01', name: '锐见', subtitle: '商务蓝 · 专业信赖',
    industry: 'service', subcategory: '咨询', tags: ['咨询', '商务', '专业'],
    primaryColor: '#1E3A5F', secondaryColor: '#2C5F8A', accentColor: '#C9A87C',
    neutralColor: '#6B7280', bgColor: '#F8FAFC',
    fonts: { heading: 'Inter', body: 'Noto Sans SC' },
    logoText: '锐见', logoIcon: '棱镜+光线',
    pricing: { basic: 149, standard: 299, premium: 599 },
    creator: 'Spark 官方', sales: 198, rating: 4.7, isExclusive: false, isNew: false, isFeatured: false,
    story: '洞察本质，锐意前行。为企业提供清晰的战略视角。',
    designConcept: '深蓝+金色点缀，无衬线体传递理性与专业。',
    mockups: { card: '深蓝烫金名片', storefront: '写字楼铭牌', phone: '企业官网', packaging: '报告封面' },
  },

  // ===== 生活方式 =====
  {
    id: 'vi_camp_01', name: '野趣', subtitle: '户外自然 · 自由探索',
    industry: 'lifestyle', subcategory: '露营', tags: ['露营', '户外', '自然'],
    primaryColor: '#2D6A4F', secondaryColor: '#95D5B2', accentColor: '#D4A373',
    neutralColor: '#6C757D', bgColor: '#F5FFF5',
    fonts: { heading: 'Montserrat', body: 'Noto Sans SC' },
    logoText: '野趣', logoIcon: '帐篷+松树',
    pricing: { basic: 99, standard: 199, premium: 399 },
    creator: '设计师 @Momo', sales: 167, rating: 4.7, isExclusive: false, isNew: true, isFeatured: false,
    story: '城市之外，自然之中。野趣，让每一次出发都值得期待。',
    designConcept: '森林绿+大地色，粗犷手写体+户外插画风格。',
    mockups: { card: '再生纸名片', storefront: '木屋招牌', phone: '小红书露营攻略', packaging: '帆布收纳袋' },
  },
];
